#!/usr/bin/env bash

# ----------------------------------------
# DEV-TOOLS EXECUTABLE FILE INFORMATIONS :

# Name          : latex-clean.sh
# Author(s)     : Dimitri OBEID
# Version       : 1.1


# ----------------------
# SCRIPT'S DESCRIPTION :

# This script remove every files generated by the LaTeX software developments, except the ".tex" (LaTeX source files) and PDF files.

# ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; #

########################################### SOURCING PROJECT'S DEPENDENCIES ###########################################

#### BASH DEPENDENCIES

## BASH UTILS

# Feel free to source any dependencies here if needed.

## ==============================================



# /////////////////////////////////////////////////////////////////////////////////////////////// #

# ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; #

############################################# GLOBAL RESOURCES DEFINITION #############################################

########################################### PROJECT'S ARGUMENTS DEFINITIONS ###########################################

#### POSITIONAL ARGUMENTS

## SUB-CATEGORY NAME

# Feel free to define positional arguments here.

## ==============================================



# /////////////////////////////////////////////////////////////////////////////////////////////// #

#### ARRAY OF ARGUMENTS

## SUB-CATEGORY NAME

# Feel free to define an array of arguments here if needed.

## ==============================================



# /////////////////////////////////////////////////////////////////////////////////////////////// #

# ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; #

######################################## PROJECT'S GLOBAL VARIABLES DEFINITIONS #######################################

#### ARRAYS DEFINITIONS

## SUB-CATEGORY NAME

# Feel free to define arrays here if needed.

## ==============================================



# /////////////////////////////////////////////////////////////////////////////////////////////// #

#### VARIABLES DEFINITIONS

## SUB-CATEGORY NAME

# Feel free to define variables here if needed.

## ==============================================



# /////////////////////////////////////////////////////////////////////////////////////////////// #

# ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; #

########################################### PROJECT'S FUNCTIONS DEFINITIONS ###########################################

#### FUNCTIONS DEFINITION

## SUB-CATEGORY NAME

# ·············································
# Feel free to define functions here if needed.



# /////////////////////////////////////////////////////////////////////////////////////////////// #

# ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; #

######################################################### CODE ########################################################

# find docs/ -name "*.aux" -o -name "*.log" -o -name "*.fdb_latexmk" -o -name "*.fls" -o -name "*.out" -o -name "*.synctex.gz" -o -name "*.toc";

find docs/ -name "*.aux" -o -name "*.log" -o -name "*.fdb_latexmk" -o -name "*.fls" -o -name "*.out" -o -name "*.synctex.gz" -o -name "*.toc" -exec rm {} +;

declare -i command_output="${?}";

if [ "${command}" -eq 0 ]; then
	if [ "${LANG,,}" == 'de' ]; then echo ""; fi
	if [ "${LANG,,}" == 'en' ]; then echo ""; fi
	if [ "${LANG,,}" == 'es' ]; then echo ""; fi
	if [ "${LANG,,}" == 'fr' ]; then echo "Fichiers supprimés"; fi
	if [ "${LANG,,}" == 'hi' ]; then echo ""; fi
	if [ "${LANG,,}" == 'id' ]; then echo ""; fi
	if [ "${LANG,,}" == 'ja' ]; then echo ""; fi
	if [ "${LANG,,}" == 'ko' ]; then echo ""; fi
	if [ "${LANG,,}" == 'pt' ]; then echo ""; fi
	if [ "${LANG,,}" == 'tr' ]; then echo ""; fi
	if [ "${LANG,,}" == 'ru' ]; then echo ""; fi
	if [ "${LANG,,}" == 'uk' ]; then echo ""; fi
	if [ "${LANG,,}" == 'zh' ]; then echo ""; fi
fi